import { Product } from "../interfaces/Product";

// export const dummyProducts: Product[] = [
//     {
//         product_id: 1,
//         name: 'Lorem',
//         product_type : 'bestseller',
//         description:'nailsLorem ipsum dolor sit amet consectetur adipisicing elit. Ab dignissimos soluta voluptatem sunt suscipit modi?',
//         price:30,
//         discounted_price:125,
        
//         images: ['/image/wrapper/stockpolish.png'],
//         category_name : 'nails',
//     },
//     {
//         product_id: 2,
//         name: 'Ipsum',
//         product_type : 'newproduct',
//         description:'manicure Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dignissimos soluta voluptatem sunt suscipit modi?',
//         price:35,
//         discountediscounted_priced_price_percentage:25,
//         product_imgs_id: '/image/wrapper/stockpolish.png',
//         category_name : 'manicure',
//     },
//     {
//         product_id: 3,
//         name: 'Silor',
//         product_type : 'none',
//         description:'pedicure Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dignissimos soluta voluptatem sunt suscipit modi?',
//         price:40,
//         discounted_price_percentage:525,
//         product_imgs_id: '/image/wrapper/stockpolish.png',
//         category_name : 'pedicure',
//     },
//     {
//         product_id: 3,
//         name: 'Silor',
//         product_type : 'none',
//         description:'pedicure Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dignissimos soluta voluptatem sunt suscipit modi?',
//         price:40,
//         discounted_price_percentage:525,
//         product_imgs_id: '/image/wrapper/stockpolish.png',
//         category_name : 'pedicure',
//     },
//     {
//         product_id: 3,
//         name: 'Silor',
//         product_type : 'none',
//         description:'pedicure Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dignissimos soluta voluptatem sunt suscipit modi?',
//         price:40,
//         discounted_price_percentage:525,
//         product_imgs_id: '/image/wrapper/stockpolish.png',
//         category_name : 'pedicure',
//     },
//     {
//         product_id: 3,
//         name: 'Silor',
//         product_type : 'none',
//         description:'pedicure Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dignissimos soluta voluptatem sunt suscipit modi?',
//         price:40,
//         discounted_price_percentage:525,
//         product_imgs_id: '/image/wrapper/stockpolish.png',
//         category_name : 'pedicure',
//     },
//     {
//         product_id: 3,
//         name: 'Silor',
//         product_type : 'none',
//         description:'pedicure Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab dignissimos soluta voluptatem sunt suscipit modi?',
//         price:40,
//         discounted_price_percentage:525,
//         product_imgs_id: '/image/wrapper/stockpolish.png',
//         category_name : 'pedicure',
//     },
// ]